-- Run this script in the Supabase SQL Editor to create the necessary tables

-- 1. Table for Weekly Activities
CREATE TABLE IF NOT EXISTS activities (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text not null,
    type text not null, -- 'Salud', 'Veterinario', 'Social', 'Servicios'
    date_str text not null, -- 'YYYY-MM-DD'
    time_str text not null, -- 'HH:MM'
    location text not null,
    icon text -- Material Icon name
);

-- 2. Table for Site Configuration (Pharmacies, Emergency, etc.)
CREATE TABLE IF NOT EXISTS site_config (
    key text primary key,
    value text,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Insert specific initial data for Site Config
INSERT INTO site_config (key, value)
VALUES 
    ('pharmacy_info', '💊 **Farmacia Cruz Verde**\n\n📍 Av. Valparaíso 450\n🕒 Hasta las 23:00 hrs'),
    ('emergency_info', '🚑 Ambulancia/SAPU: 131\n🚒 Bomberos: 132\n🚓 Carabineros: 133')
ON CONFLICT (key) DO NOTHING;

-- 4. Insert initial Activities (from hardcoded list)
INSERT INTO activities (title, type, date_str, time_str, location, icon)
VALUES
    ('Ronda Médica Rural', 'Salud', '2025-01-20', '09:30', 'Sede Social Malalche', 'medical_services'),
    ('Operativo Sanitario (Ovinos)', 'Veterinario', '2025-01-22', '10:00', 'Sector Repocura', 'pets'),
    ('Atención en Terreno DIDECO', 'Social', '2025-01-25', '11:00', 'Posta Rucapangue', 'favorite'),
    ('Camión Aljibe (Agua)', 'Servicios', '2025-01-21', '08:00', 'Ruta S-10 Km 15', 'local_shipping');

-- 5. Enable RLS (Optional but recommended, allow public read, auth write)
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_config ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can read
CREATE POLICY "Public Read Activities" ON activities FOR SELECT USING (true);
CREATE POLICY "Public Read Config" ON site_config FOR SELECT USING (true);

-- Policy: Only authenticated users (Official/Admin) can insert/update/delete
-- Assuming using Supabase Auth or simple RLS (for now allow all authenticated, fine for this app)
CREATE POLICY "Auth Write Activities" ON activities FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth Write Config" ON site_config FOR ALL USING (auth.role() = 'authenticated');
